---

- name: apt-get update
  apt:
    update_cache: yes


- name: apt-get upgrade
  apt:
    upgrade: dist

- name: install software
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - git
    - sshpass
    - python-pip
    - python-dev
    - libffi-dev
    - libssl-dev
